import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import StateContextProvider from "./appcontext";
import { SkeletonNavbar } from "./component/navbar";
import dynamic from "next/dynamic";
import { Suspense } from "react";
import Footer from "./component/navbar/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Navbar = dynamic(() => import("./component/navbar/index"), {
  ssr: false,
  loading: () => <SkeletonNavbar />,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StateContextProvider>
          <Suspense fallback={<SkeletonNavbar />}>
            <Navbar />
          </Suspense>
          {children}
          <Footer />
        </StateContextProvider>
      </body>
    </html>
  );
}
